#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# python /app/manage.py flush --no-input
python /app/manage.py migrate
python /app/manage.py collectstatic --noinput

exec "$@"

python /app/manage.py runserver 0.0.0.0:8000
#/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
