# Generated by Django 4.0.6 on 2022-07-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_alter_node_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='org_unit',
        ),
        migrations.AddField(
            model_name='node',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrganisationalUnitModel',
        ),
    ]
