# Generated by Django 4.0.6 on 2022-07-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0003_remove_node_org_unit_node_description_node_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
